filebeat.inputs:
- type: log
  paths:
    - "/var/log/app_logs/*.log"
  tail_files: true
  close_inactive: 1h
  ignore_older: 2h
  clean_inactive: 3h
  fields:
    type: "app_logs"
      
output.logstash:
  enabled: true
  hosts: 'engine:5044'

output.elasticsearch:
  enabled: false
